export const img = {
  RightArrow: require('../assets/images/ArrowRight2.png'),
  profile: require('../assets/images/Profile.png'),
  HidePassword: require('../assets/images/Hide-Password.png'),
  Eye: require('../assets/images/eye.png'),
  Lock: require('../assets/images/Lock.png'),
  Message: require('../assets/images/Message.png'),
  EmptyBox: require('../assets/images/EmptyBox.png'),
  CheckBox: require('../assets/images/CheckBox.png'),
  google: require('../assets/images/google.png'),
  facebook: require('../assets/images/facebook.png'),
  Login: require('../assets/images/Login.png'),
  chat: require('../assets/images/chat.png'),
  setting: require('../assets/images/setting.png'),
  boy: require('../assets/images/boy.png'),
  back: require('../assets/images/back.png'),
  plus: require('../assets/images/plus.png'),
  send: require('../assets/images/send.png'),
  splashLogo: require('../assets/images/splashLogo.png'),
  plane: require('../assets/images/plane.png'),
  grouplogo: require('../assets/images/grouplogo.png'),
  logoutimg: require('../assets/images/logout.png'),

  // vector: require('../assets/images/Vector.png'),
  // User: require('../assets/images/User2.png'),
};
